/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gles_rohit_Common_jassimp2_Jassimp */

#ifndef _Included_com_gles_rohit_Common_jassimp2_Jassimp
#define _Included_com_gles_rohit_Common_jassimp2_Jassimp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getVKeysize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getVKeysize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getQKeysize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getQKeysize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getV3Dsize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getV3Dsize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getfloatsize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getfloatsize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getintsize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getintsize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getuintsize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getuintsize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getdoublesize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getdoublesize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getlongsize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getlongsize
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    getErrorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_getErrorString
  (JNIEnv *, jclass);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    aiImportFile
 * Signature: (Ljava/lang/String;J)Lcom/gles/rohit/Common/jassimp2/AiScene;
 */
JNIEXPORT jobject JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_aiImportFile
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    aiImportFileEx
 * Signature: (Ljava/lang/String;JLcom/gles/rohit/Common/jassimp2/JassimpFileIO;)Lcom/gles/rohit/Common/jassimp2/AiScene;
 */
JNIEXPORT jobject JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_aiImportFileEx
  (JNIEnv *, jclass, jstring, jlong, jobject);

/*
 * Class:     com_gles_rohit_Common_jassimp2_Jassimp
 * Method:    aiImportAssetFile
 * Signature: (Ljava/lang/String;JLandroid/content/res/AssetManager;)Lcom/gles/rohit/Common/jassimp2/AiScene;
 */
JNIEXPORT jobject JNICALL Java_com_gles_rohit_Common_jassimp2_Jassimp_aiImportAssetFile
  (JNIEnv *, jclass, jstring, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
